<?php

/**
 * This is the model base class for the table "{{product_description}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductDescription".
 *
 * Columns in table "{{product_description}}" available as properties of the model,
 * followed by relations of table "{{product_description}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $product_id
 * @property string $description
 *
 * @property Product $product
 */
abstract class BaseProductDescription extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{product_description}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProductDescription|ProductDescriptions', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('description', 'required'),
			array('product_id', 'numerical', 'integerOnly'=>true),
			array('product_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, product_id, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'product' => array(self::BELONGS_TO, 'Product', 'product_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'product_id' => null,
			'description' => Yii::t('app', 'Description'),
			'product' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}