<?php

/**
 * This is the model base class for the table "{{category_info}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CategoryInfo".
 *
 * Columns in table "{{category_info}}" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id
 * @property integer $category_id
 * @property string $description
 *
 */
abstract class BaseCategoryInfo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{category_info}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CategoryInfo|CategoryInfos', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('category_id', 'numerical', 'integerOnly'=>true),
			array('description', 'safe'),
			array('category_id, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, category_id, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
        return array(
        );
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'category_id' => null,
			'description' => Yii::t('app', 'Description'),
            'category' => null,

        );
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('category_id', $this->category_id);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}