<?php

/**
 * This is the model base class for the table "{{catalogue_property_value}}".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CataloguePropertyValue".
 *
 * Columns in table "{{catalogue_property_value}}" available as properties of the model,
 * followed by relations of table "{{catalogue_property_value}}" available as properties of the model.
 *
 * @property integer $id
 * @property integer $product_id
 * @property integer $property_id
 * @property string $value
 *
 * @property CatalogueProperty $property
 * @property CatalogueProduct $product
 */
abstract class BaseCataloguePropertyValue extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return '{{catalogue_property_value}}';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CataloguePropertyValue|CataloguePropertyValues', $n);
	}

	public static function representingColumn() {
		return 'value';
	}

	public function rules() {
		return array(
			array('value', 'required'),
			array('product_id, property_id', 'numerical', 'integerOnly'=>true),
			array('value', 'length', 'max'=>255),
			array('product_id, property_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, product_id, property_id, value', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'property' => array(self::BELONGS_TO, 'CatalogueProperty', 'property_id'),
			'product' => array(self::BELONGS_TO, 'CatalogueProduct', 'product_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'product_id' => null,
			'property_id' => null,
			'value' => Yii::t('app', 'Value'),
			'property' => null,
			'product' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('property_id', $this->property_id);
		$criteria->compare('value', $this->value, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}